#!/usr/bin/env ruby

# frozen_string_literal: true

require 'thor'
require 'colorize'
require_relative 'lib/common'
require_relative 'lib/rspecdatshit'
require_relative 'lib/utils'
require_relative 'lib/decidim'

# Bruw is a simple CLI for daily commands
class Bruw < Thor
  desc 'datshit SUBCOMMAND ...ARGS', 'run easily modified specs using rspec'
  subcommand 'datshit', RspecDatShit

  desc 'utils SUBCOMMAND ...ARGS', 'useful commands'
  subcommand 'utils', Utils

  desc 'dcd SUBCOMMAND ...ARGS', 'useful commands'
  subcommand 'dcd', Decidim
end

Bruw.start(ARGV)
