#!/usr/bin/env ruby

# frozen_string_literal: true

require 'thor'
require 'colorize'
require_relative 'lib/common'
require_relative 'lib/rspecdatshit'

# Bruw is a simple CLI for daily commands
class Bruw < Thor
  desc 'datshit SUBCOMMAND ...ARGS', 'run easily modified specs using rspec'
  subcommand 'datshit', RspecDatShit
end

Bruw.start(ARGV)
