name: Tests
on:
  push:
    branches:
      - develop
      - master
      - release/*
      - "*-stable"

env:
  CI: "true"
  RUBY_VERSION: 2.7.1

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@v0.2.2
        if: "github.ref != 'refs/heads/master' || github.ref != 'refs/heads/develop'"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - uses: nanasess/setup-chromedriver@v1.0.1
      - run: bundle exec rspec
